/**
 * This code is auto generated by boj-helper-in-java v.0.02 
 * Anyone can join this simple open-source project any time*
 *
 * github : https://github.com/Chwangsky
 */ 

import java.io.*;

public class Main {
    public static void main(String[] args) throws IOException {

        MySolution solution = new MySolution();
        solution.solution();

    }
}

class MySolution {

    public BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
    public BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(System.out));

    public MySolution() {
    }

    public MySolution(BufferedReader br, BufferedWriter bw) {
        this.br = br;
        this.bw = bw;
    }

    

    public void solution() throws IOException {
        String[] s = br.readLine().split(" ");

        int answer = 0;
        for (int i = 0; i < s.length; i++) {
            answer += Integer.parseInt(s[i]);
        }
        bw.write(String.valueOf(answer));
        bw.flush();
        bw.close();

    }

}